- name: Render /etc/dnsmasq.conf file
  ansible.builtin.template:
    src: ./templates/dnsmasq.conf.j2
    dest: "/etc/dnsmasq.conf"
    owner: root
    group: root
    mode: '0644'
  when: 
  - ansible_os_family == "Debian"
  - fw_dnsmasq_ipset_enabled | default(false)
  become: true

- name: Enable / (Re)Start dnsmasq service
  ansible.builtin.systemd:
    name: dnsmasq.service
    enabled: true
    state: restarted
  when: 
  - ansible_os_family == "Debian"
  - fw_dnsmasq_ipset_enabled | default(false)
  become: true