# Connection State Tracking Configs
- name: IPTABLES - Connection State Tracking - INPUT
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - '-A INPUT -m state --state INVALID -j LOG --log-prefix "DROP_INPUT INVALID " --log-ip-options --log-tcp-options'
  - '-A INPUT -m state --state INVALID -j DROP'
  - '-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT'
  become: true

- name: IPTABLES - Connection State Tracking - OUTPUT
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - '-A OUTPUT -m state --state INVALID -j LOG --log-prefix "DROP_OUTPUT INVALID " --log-ip-options --log-tcp-options'
  - '-A OUTPUT -m state --state INVALID -j DROP'
  - '-A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT'
  become: true

- name: IPTABLES - Connection State Tracking - FORWARD
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - '-A FORWARD -m state --state INVALID -j LOG --log-prefix "DROP_FORWARD INVALID " --log-ip-options --log-tcp-options'
  - '-A FORWARD -m state --state INVALID -j DROP'
  - '-A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT'
  become: true