---
- name: Render /usr/local/sbin/iptablesV4.sh script
  ansible.builtin.template:
    src: ./templates/iptablesV4.sh.j2
    dest: "/usr/local/sbin/iptablesV4.sh"
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Execute iptablesV4.sh script
  ansible.builtin.shell: 
    cmd: nohup /usr/local/sbin/iptablesV4.sh </dev/null >/dev/null 2>&1 &
  become: true

- name: Wait for the ssh port and reconnect 
  wait_for:
    port: '{{ ansible_ssh_port|default("22") }}'
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    delay: 10
    timeout: 60
    state: started
  become: no
  connection: local