---
- name: IPTABLES - OUTBOUND FTP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -p tcp --dport 21 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_ftp | default(true)
  become: true

- name: IPTABLES - OUTBOUND SMTP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -p tcp --dport 25 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_smtp | default(true)
  become: true

- name: IPTABLES - OUTBOUND HTTP 
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -p tcp --dport 443 --syn -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp --dport 8443 --syn -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp --dport 80 --syn -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp --dport 8080 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_http | default(true)
  become: true

- name: IPTABLES - OUTBOUND DNS Queries
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  ## DNS Queries...
  - "-A OUTPUT -p udp -m udp --dport 53 -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp -m tcp --dport 53 -m state --state NEW -j ACCEPT"
  ## Whois Lookups... 
  - "-A OUTPUT -p tcp --dport 43 --syn -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp --dport 4321 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_dns | default(true)
  become: true

- name: IPTABLES - OUTBOUND DHCP Queries
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  ## DNS Queries...
  - "-A OUTPUT -p udp -m udp --dport 67 -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp -m tcp --dport 67 -m state --state NEW -j ACCEPT"
  when: fw_outbound_dhcp | default(true)
  become: true

- name: IPTABLES - OUTBOUND ICMP Rquest
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT"
  when: fw_outbound_icmp_req | default(true)
  become: true

# Output rules from localhost
#-A OUTPUT -o lo -j LO-OUTPUT-LO
- name: IPTABLES - OUTBOUND rules - User Defined
  ansible.builtin.shell: "iptables {{ item }}"
  with_items: "{{ fw_iptables_extra_outbound_rules }}"
  become: true

# Allow helper ports for traceroutes
- name: IPTABLES - OUTBOUND Traceroutes
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -p udp --dport 33434:33626 -j ACCEPT"
  when: fw_outbound_traceroutes | default(true)
  become: true

- name: IPTABLES - OUTBOUND Interprocess Chain
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -o lo -j LO-OUTPUT-LO"
  become: true

# Default OUTPUT log rule
- name: IPTABLES - OUTBOUND Log DROPs Rule
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A OUTPUT -o '!lo' -j LOG --log-prefix \"DROP \" --log-ip-options --log-tcp-options"
  become: true