--- 
- name: IPTABLES - Allow SSH from WAN (default) Net
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i {{ fw_wan_if }} -s {{ fw_wan_net_cidr }} -p tcp --dport 22 --syn -m state --state NEW -j ACCEPT"
  when: fw_ssh_from_wan_net_enabled
  become: true

- name: IPTABLES - Allow SSH from OFFICE Net
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i {{ fw_office_if }} -s {{ fw_office_net_cidr }} -p tcp --dport 22 --syn -m state --state NEW -j ACCEPT"
  when: fw_office_net_enabled and fw_ssh_from_office_net_enabled
  become: true

- name: IPTABLES - Allow SSH from SERVER Net
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i {{ fw_server_if }} -s {{ fw_server_net_cidr }} -p tcp --dport 22 --syn -m state --state NEW -j ACCEPT"
  when: fw_server_net_enabled and fw_ssh_from_server_net_enabled
  become: true

- name: IPTABLES - Allow SSH from FAMILY Net
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i {{ fw_family_if }} -s {{ fw_family_net_cidr }} -p tcp --dport 22 --syn -m state --state NEW -j ACCEPT"
  when: fw_family_net_enabled and fw_ssh_from_family_net_enabled
  become: true

- name: IPTABLES - Allow SSH from DMZ Net
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i {{ fw_dmz_if }} -s {{ fw_dmz_net_cidr }} -p tcp --dport 22 --syn -m state --state NEW -j ACCEPT"
  when: fw_dmz_net_enabled and fw_ssh_from_dmz_net_enabled
  become: true