---
- name: Update repositories cache and install bind9 packages
  apt:
    name:
    - dnsmasq
    update_cache: yes
  become: true
  when:
  - ansible_os_family == "Debian"
  - fw_dnsmasq_ipset_enabled | default(false)