---
### NOTE: IPTABLES and Modprobe commands are run synchronously from top down using ansible.builtin.shell
- name: MODPROBE - Enable modules
  ansible.builtin.shell: modprobe {{ item }}
  with_items:
    - ip_conntrack
    - iptable_nat
  become: true

- name: IP6TABLES - temporary configure default ACCEPT on tables
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-P INPUT ACCEPT"
  - "-P OUTPUT ACCEPT"
  - "-P FORWARD ACCEPT"
  become: true

- name: IP6TABLES - Flush all rules in filter and NAT tables
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "--flush"
  - "--table nat --flush"
  - "-X"
  become: true

# Default DROP
- name: IP6TABLES - Configure default DROP on tables
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-P INPUT DROP"
  - "-P OUTPUT DROP"
  - "-P FORWARD DROP"
  become: true

# Outbound rules (from this machine)
- include_tasks: outbound.yaml

# Inbound rules (to this machine - excludes FORWARDING)
- include_tasks: inbound.yaml