---
- name: IP6TABLES - OUTBOUND FTP
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-A OUTPUT -p tcp --dport 21 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_ftp | default(true)
  become: true

- name: IP6TABLES - OUTBOUND SMTP
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-A OUTPUT -p tcp --dport 25 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_smtp | default(true)
  become: true

- name: IP6TABLES - OUTBOUND HTTP 
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-A OUTPUT -p tcp --dport 443 --syn -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp --dport 80 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_http | default(true)
  become: true

- name: IP6TABLES - OUTBOUND DNS Queries
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  ## DNS Queries...
  - "-A OUTPUT -p udp -m udp --dport 53 -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp -m tcp --dport 53 -m state --state NEW -j ACCEPT"
  ## Whois Lookups... 
  - "-A OUTPUT -p tcp --dport 43 --syn -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp --dport 4321 --syn -m state --state NEW -j ACCEPT"
  when: fw_outbound_dns | default(true)
  become: true

- name: IP6TABLES - OUTBOUND DHCP Queries
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  ## DNS Queries...
  - "-A OUTPUT -p udp -m udp --dport 67 -m state --state NEW -j ACCEPT"
  - "-A OUTPUT -p tcp -m tcp --dport 67 -m state --state NEW -j ACCEPT"
  when: fw_outbound_dhcp | default(true)
  become: true

- name: IP6TABLES - OUTBOUND ICMP Rquest
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-A OUTPUT -p icmpv6 --icmpv6-type echo-request -j ACCEPT"
  when: fw_outbound_icmp_req | default(true)
  become: true

# Default OUTPUT log rule
- name: IP6TABLES - OUTBOUND Log DROPs Rule
  ansible.builtin.shell: "ip6tables {{ item }}"
  with_items:
  - "-A OUTPUT -o '!lo' -j LOG --log-prefix \"DROP \" --log-ip-options --log-tcp-options"
  become: true