---
### Inbound from Office Net Rules
- name: IPTABLES - INBOUND from Office Net - DNS
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p tcp -i {{ fw_office_if }} -s {{ fw_office_net_cidr }} --dport 53 --syn -m state --state NEW -j ACCEPT"
  - "-A INPUT -p udp -i {{ fw_office_if }} -s {{ fw_office_net_cidr }} --dport 53 -m state --state NEW -j ACCEPT"
  when: fw_dns_server and fw_office_net_enabled
  become: true

- name: IPTABLES - INBOUND from Office Net - DHCP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_office_if }} -s {{ fw_office_net_cidr }} --dport 67 -m state --state NEW -j ACCEPT"
  when: fw_dhcp_server and fw_office_net_enabled
  become: true

- name: IPTABLES - INBOUND from Office Net - ICMP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p icmp -i {{ fw_office_if }} -s {{ fw_office_net_cidr }} --icmp-type echo-request -j ACCEPT"
  when: fw_office_net_enabled
  become: true

- name: IPTABLES - INBOUND from Office Net - traceroute helper
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_office_if }} -s {{ fw_office_net_cidr }} --dport 33434:33626 -j REJECT"
  when: fw_office_net_enabled and fw_net_allow_traceroutes | default(true)
  become: true

### Inbound from Server Net Rules
- name: IPTABLES - INBOUND from Server Net - DNS
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p tcp -i {{ fw_server_if }} -s {{ fw_server_net_cidr }} --dport 53 --syn -m state --state NEW -j ACCEPT"
  - "-A INPUT -p udp -i {{ fw_server_if }} -s {{ fw_server_net_cidr }} --dport 53 -m state --state NEW -j ACCEPT"
  when: fw_dns_server and fw_server_net_enabled
  become: true

- name: IPTABLES - INBOUND from Server Net - DHCP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_server_if }} -s {{ fw_server_net_cidr }} --dport 67 -m state --state NEW -j ACCEPT"
  when: fw_dhcp_server and fw_server_net_enabled
  become: true

- name: IPTABLES - INBOUND from Server Net - ICMP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p icmp -i {{ fw_server_if }} -s {{ fw_server_net_cidr }} --icmp-type echo-request -j ACCEPT"
  when: fw_server_net_enabled
  become: true

- name: IPTABLES - INBOUND from Server Net - traceroute helper
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_server_if }} -s {{ fw_server_net_cidr }} --dport 33434:33626 -j REJECT"
  when: fw_server_net_enabled and fw_net_allow_traceroutes | default(true)
  become: true

### Inbound from Family Net Rules
- name: IPTABLES - INBOUND from Family Net - DNS
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p tcp -i {{ fw_family_if }} -s {{ fw_family_net_cidr }} --dport 53 --syn -m state --state NEW -j ACCEPT"
  - "-A INPUT -p udp -i {{ fw_family_if }} -s {{ fw_family_net_cidr }} --dport 53 -m state --state NEW -j ACCEPT"
  when: fw_dns_server and fw_family_net_enabled
  become: true

- name: IPTABLES - INBOUND from Family Net - DHCP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_family_if }} -s {{ fw_family_net_cidr }} --dport 67 -m state --state NEW -j ACCEPT"
  when: fw_dhcp_server and fw_family_net_enabled
  become: true

- name: IPTABLES - INBOUND from Family Net - ICMP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p icmp -i {{ fw_family_if }} -s {{ fw_family_net_cidr }} --icmp-type echo-request -j ACCEPT"
  when: fw_family_net_enabled
  become: true

- name: IPTABLES - INBOUND from Family Net - traceroute helper
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_family_if }} -s {{ fw_family_net_cidr }} --dport 33434:33626 -j REJECT"
  when: fw_family_net_enabled and fw_net_allow_traceroutes | default(true)
  become: true

### Inbound from DMZ Net Rules
- name: IPTABLES - INBOUND from DMZ Net - DNS
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p tcp -i {{ fw_dmz_if }} -s {{ fw_dmz_net_cidr }} --dport 53 --syn -m state --state NEW -j ACCEPT"
  - "-A INPUT -p udp -i {{ fw_dmz_if }} -s {{ fw_dmz_net_cidr }} --dport 53 -m state --state NEW -j ACCEPT"
  when: fw_dns_server and fw_dmz_net_enabled
  become: true

- name: IPTABLES - INBOUND from DMZ Net - DHCP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_dmz_if }} -s {{ fw_dmz_net_cidr }} --dport 67 -m state --state NEW -j ACCEPT"
  when: fw_dhcp_server and fw_dmz_net_enabled
  become: true

- name: IPTABLES - INBOUND from DMZ Net - ICMP
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p icmp -i {{ fw_dmz_if }} -s {{ fw_dmz_net_cidr }} --icmp-type echo-request -j ACCEPT"
  when: fw_dmz_net_enabled
  become: true

- name: IPTABLES - INBOUND from DMZ Net - traceroute helper
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -p udp -i {{ fw_dmz_if }} -s {{ fw_dmz_net_cidr }} --dport 33434:33626 -j REJECT"
  when: fw_dmz_net_enabled and fw_net_allow_traceroutes | default(true)
  become: true

## Inter-process Communication
- name: IPTABLES - INBOUND Interprocess Chain
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i lo -j LO-INPUT-LO"
  become: true

## Inbound Rules from WAN Go Here:

## Default OUTPUT log rule
- name: IPTABLES - INBOUND Log DROPs Rule
  ansible.builtin.shell: "iptables {{ item }}"
  with_items:
  - "-A INPUT -i '!lo' -j LOG --log-prefix \"DROP \" --log-ip-options --log-tcp-options"
  become: true