---
- hosts: all
  become: true
  tasks:
    - debug: 
        var: ansible_os_family


- hosts: firewall
  become: true

  tasks:
    - set_fact:
        role: "I'm a firewall!"

    - include_role:
        name: "iptables/rocky"
      when: ansible_os_family == "Rocky"

    - include_role:
        name: "iptables/debian"
      when: ansible_os_family == "Debian"