---
- hosts: firewall
  become: true
  tasks:
    - debug: 
        var: ansible_os_family

    - debug:
        var: fw_dns_server
    - debug:
        var: fw_dhcp_server
    - debug:
        var: fw_ssh_from_wan_net_enabled

    - include_role:
        name: "netfacts"

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: "iptables/rocky"
      when: ansible_os_family == "Rocky"

    - include_role:
        name: "iptables/debian"
      when: ansible_os_family == "Debian"

    - include_role:
        name: "iptables/rules"

    - include_role:
        name: "iptables/save"

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: "dns/install"

    - include_role:
        name: "dns/config"

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: "dhcpd/install"

    - include_role:
        name: "dhcpd/config"