---
- hosts: firewall
  become: true
  gather_facts: true
  tasks:
    - debug: 
        var: ansible_os_family

    - debug:
        var: fw_dns_server
    - debug:
        var: fw_dhcp_server
    - debug:
        var: fw_ssh_from_wan_net_enabled

    - include_role:
        name: "netfacts"

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: ipset/install
      when: 
      - fw_ipset_enabled | default(true)
      - fw_iptables_enabled | default(true)

    - include_role:
        name: ipset/config
      when: 
      - fw_ipset_enabled | default(true)
      - fw_iptables_enabled | default(true)

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: "iptables/rocky"
      when: 
      - ansible_os_family == "Rocky"
      - fw_iptables_enabled | default(true)

    - include_role:
        name: "iptables/debian"
      when:
      - ansible_os_family == "Debian"
      - fw_iptables_enabled | default(true)

    - include_role:
        name: "iptables/rules_v4"
      when:
      - fw_iptables_enabled | default(true)
    
    - include_role:
        name: "iptables/rules_v6"
      when:
      - fw_iptables_enabled | default(true)

    - include_role:
        name: "iptables/save"
      when:
      - fw_iptables_enabled | default(true)

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: "dns/install"

    - include_role:
        name: "dns/config"

    - include_role:
        name: "dnsmasq/install"

    - include_role:
        name: "dnsmasq/config"

- hosts: firewall
  become: true

  tasks:
    - include_role:
        name: "dhcpd/install"

    - include_role:
        name: "dhcpd/config"